create table if not exists public.patient_wig_safety_assessments (
  assessment_id integer generated by default as identity primary key,
  req_id integer not null unique,
  has_known_allergies boolean,
  allergy_details text,
  has_sensitive_scalp boolean,
  has_scalp_irritation boolean,
  has_open_scalp_wounds boolean,
  has_medical_restriction boolean,
  medical_restriction_details text,
  information_confirmed boolean not null default false,
  confirmed_at timestamp with time zone,
  review_status character varying(30) not null default 'Pending',
  reviewed_by integer,
  reviewed_at timestamp with time zone,
  review_notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint wig_safety_request_fkey
    foreign key (req_id) references public."Wig_Requests" ("Req_ID") on delete cascade,
  constraint wig_safety_reviewer_fkey
    foreign key (reviewed_by) references public.users (user_id),
  constraint patient_wig_safety_assessments_review_status_check
    check (review_status in ('Pending', 'Cleared', 'Needs Clarification', 'Requires Medical Clearance'))
);
alter table public.patient_wig_safety_assessments enable row level security;
grant select, insert, update on public.patient_wig_safety_assessments to authenticated;
grant usage, select on sequence public.patient_wig_safety_assessments_assessment_id_seq to authenticated;
drop policy if exists "patients_read_own_wig_safety_assessment" on public.patient_wig_safety_assessments;
create policy "patients_read_own_wig_safety_assessment"
on public.patient_wig_safety_assessments
for select
using (
  public.current_app_user_is_staff()
  or exists (
    select 1
    from public."Wig_Requests" wr
    join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
    where wr."Req_ID" = patient_wig_safety_assessments.req_id
      and p."User_ID" = public.current_app_user_id()
  )
);
drop policy if exists "patients_insert_own_wig_safety_assessment" on public.patient_wig_safety_assessments;
create policy "patients_insert_own_wig_safety_assessment"
on public.patient_wig_safety_assessments
for insert
with check (
  review_status = 'Pending'
  and reviewed_by is null
  and reviewed_at is null
  and exists (
    select 1
    from public."Wig_Requests" wr
    join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
    where wr."Req_ID" = patient_wig_safety_assessments.req_id
      and p."User_ID" = public.current_app_user_id()
  )
);
drop policy if exists "patients_update_own_pending_wig_safety_assessment" on public.patient_wig_safety_assessments;
create policy "patients_update_own_pending_wig_safety_assessment"
on public.patient_wig_safety_assessments
for update
using (
  review_status = 'Pending'
  and exists (
    select 1
    from public."Wig_Requests" wr
    join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
    where wr."Req_ID" = patient_wig_safety_assessments.req_id
      and p."User_ID" = public.current_app_user_id()
  )
)
with check (
  review_status = 'Pending'
  and reviewed_by is null
  and reviewed_at is null
  and exists (
    select 1
    from public."Wig_Requests" wr
    join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
    where wr."Req_ID" = patient_wig_safety_assessments.req_id
      and p."User_ID" = public.current_app_user_id()
  )
);
drop policy if exists "staff_review_wig_safety_assessments" on public.patient_wig_safety_assessments;
create policy "staff_review_wig_safety_assessments"
on public.patient_wig_safety_assessments
for update
using (public.current_app_user_is_staff())
with check (public.current_app_user_is_staff());
