-- Patient AI wig preview request schema support.
-- The mobile patient request flow writes selected wig details and generated preview URL
-- to Wig_Request_Specifications after creating a Wig_Requests row.

create table if not exists public."Wig_Request_Specifications" (
  "Req_Spec_ID" integer generated by default as identity primary key,
  "Req_ID" integer not null unique references public."Wig_Requests"("Req_ID") on delete cascade,
  "Preferred_Color" character varying,
  "Preferred_Length" character varying,
  "Hair_Texture" character varying,
  "Cap_Size" character varying,
  "Style_Preference" character varying,
  "Special_Notes" text,
  "AI_Wig_Preview_URL" text,
  "Created_At" timestamp without time zone not null default now(),
  "Updated_At" timestamp without time zone not null default now()
);
alter table public."Wig_Request_Specifications" enable row level security;
grant select, insert, update on public."Wig_Request_Specifications" to authenticated;
do $$
begin
  if to_regclass('public."Wig_Request_Specifications_Req_Spec_ID_seq"') is not null then
    grant usage, select on sequence public."Wig_Request_Specifications_Req_Spec_ID_seq" to authenticated;
  end if;
end;
$$;
drop policy if exists "patients_read_own_wig_request_specifications" on public."Wig_Request_Specifications";
create policy "patients_read_own_wig_request_specifications"
on public."Wig_Request_Specifications"
for select
using (
  public.current_app_user_is_staff()
  or exists (
    select 1
    from public."Wig_Requests" wr
    join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
    where wr."Req_ID" = "Wig_Request_Specifications"."Req_ID"
      and p."User_ID" = public.current_app_user_id()
  )
);
drop policy if exists "patients_insert_own_wig_request_specifications" on public."Wig_Request_Specifications";
create policy "patients_insert_own_wig_request_specifications"
on public."Wig_Request_Specifications"
for insert
with check (
  exists (
    select 1
    from public."Wig_Requests" wr
    join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
    where wr."Req_ID" = "Wig_Request_Specifications"."Req_ID"
      and p."User_ID" = public.current_app_user_id()
      and lower(trim(coalesce(wr."Status", 'pending'))) = 'pending'
  )
);
drop policy if exists "patients_update_own_wig_request_specifications" on public."Wig_Request_Specifications";
create policy "patients_update_own_wig_request_specifications"
on public."Wig_Request_Specifications"
for update
using (
  public.current_app_user_is_staff()
  or exists (
    select 1
    from public."Wig_Requests" wr
    join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
    where wr."Req_ID" = "Wig_Request_Specifications"."Req_ID"
      and p."User_ID" = public.current_app_user_id()
      and lower(trim(coalesce(wr."Status", 'pending'))) = 'pending'
  )
)
with check (
  public.current_app_user_is_staff()
  or exists (
    select 1
    from public."Wig_Requests" wr
    join public."Patients" p on p."Patient_ID" = wr."Patient_ID"
    where wr."Req_ID" = "Wig_Request_Specifications"."Req_ID"
      and p."User_ID" = public.current_app_user_id()
      and lower(trim(coalesce(wr."Status", 'pending'))) = 'pending'
  )
);
create or replace function public.set_wig_request_code()
returns trigger
language plpgsql
as $$
begin
  if new."Request_Code" is null or trim(new."Request_Code") = '' then
    new."Request_Code" := 'WR' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6));
  end if;

  return new;
end;
$$;
drop trigger if exists set_wig_request_code_before_insert on public."Wig_Requests";
create trigger set_wig_request_code_before_insert
before insert on public."Wig_Requests"
for each row
execute function public.set_wig_request_code();
