-- Donor feedback records submitted from the mobile donor app.

create table if not exists public."Donor_Feedback" (
  "Feedback_ID" bigint generated by default as identity primary key,
  "User_ID" bigint not null references public.users(user_id) on delete cascade,
  "Feedback_Type" text not null,
  "Message" text not null,
  "Source_Route" text not null default '/donor/feedback',
  "App_Role" text not null default 'donor',
  "Status" text not null default 'New',
  "Created_At" timestamptz not null default now(),
  "Updated_At" timestamptz not null default now(),
  constraint "Donor_Feedback_Type_check"
    check ("Feedback_Type" in ('issue', 'suggestion', 'experience')),
  constraint "Donor_Feedback_Message_length_check"
    check (char_length(trim("Message")) between 10 and 2000),
  constraint "Donor_Feedback_Status_check"
    check ("Status" in ('New', 'Reviewed', 'Resolved', 'Archived'))
);
alter table public."Donor_Feedback" enable row level security;
grant select, insert, update on public."Donor_Feedback" to authenticated;
grant usage, select on sequence public."Donor_Feedback_Feedback_ID_seq" to authenticated;
drop policy if exists "donors_insert_own_feedback" on public."Donor_Feedback";
create policy "donors_insert_own_feedback"
on public."Donor_Feedback"
for insert
with check (
  "User_ID" = public.current_app_user_id()
  and "App_Role" = 'donor'
  and "Status" = 'New'
);
drop policy if exists "donors_read_own_feedback" on public."Donor_Feedback";
create policy "donors_read_own_feedback"
on public."Donor_Feedback"
for select
using (
  public.current_app_user_is_staff()
  or "User_ID" = public.current_app_user_id()
);
drop policy if exists "staff_update_feedback_status" on public."Donor_Feedback";
create policy "staff_update_feedback_status"
on public."Donor_Feedback"
for update
using (public.current_app_user_is_staff())
with check (public.current_app_user_is_staff());
